name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Clang 18 and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-21 g++-14

      - name: Configure CMake
        env:
          CC: clang-21
          CXX: clang++-21
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=26 -DCMAKE_CXX_STANDARD_REQUIRED=ON

      - name: Compiling
        run: cmake --build build --config Release

      - name: Run
        run: ./build/MyGit
